### ISSUE TITLE
Rename karaf-features-gen to gradle-karaf-plugin

### ISSUE THREAD

**Issue by lburgazzoli** [lburgazzoli/gradle-karaf-features-plugin#9]
@sebersole any problem if I rename the plugin to  gradle-karaf-plugin

**Comment by sebersole** [comment]
It is generally considered bad for to have gradle in the name of a gradle
plugin

**Comment by lburgazzoli** [comment]
I meat to have gradle-karaf-plugin as artifact-id and project name

**Comment by sebersole** [comment]
I'll turn that question back around on you.. :)  If you saw a project named gradle-karaf-plugin what would you think it did?  To me that name implies somehow running Karaf from Gradle.

**Comment by lburgazzoli** [comment]
You are right but that is not different from the official karaf-maven-plugin. 

Then if I want to add also kar and custom karaf distribution tasks, would you get it from karaf-feature-gen ? :-)

If you know a better name please share :-)

**Comment by sebersole** [comment]
Maven essentially requires plugins to have maven in their name (or at least
used to) because its how they automatically recognize plugin short naming.
And it is an awful idea to base naming conventions on Maven :)

I barely know what a KAR file is.  After you mentioned it I read and
determined that it is a Karaf features repository (just like the XML) that
also bundles the bundle jars).  So personally, knowing what a KAR and
understanding Karaf feature repositories I would absolutely get that from
the name karaf-features-gen.

I have no idea what a "Karaf distribution" is.  But I think you need to be
careful about bundling so much unrelated stuff in one plugin.  Generating a
feature repo XML and a feature repo archive are obviously completely
related concepts.  I guess it depends what this "Karaf distribution"
concept is.

**Comment by lburgazzoli** [comment]
would karaf-features-plugin sound better? I do not like the '-gen' :-)

**Comment by lburgazzoli** [comment]
At the end I've renamed the whole project, btw I found that hibernate uses "gradle-" in artifact id :-)

**Comment by sebersole** [comment]
Way to be selective to back up your argument :)  I have created many many
many plugins.  Yes my initial one used gradle in the name.  I do this thing
called learning from my mistakes :)

**Comment by lburgazzoli** [comment]
I'd love a better naming but at the moment is the one that fits the conventions we are using so I did it :-) a little rude I know

**Comment by sebersole** [comment]
no worries.  if I ever get fed up I'll just fork it :)

**Comment by lburgazzoli** [comment]
Hope not :-) 
Hope to see some more contributions in the future
